### ISSUE TITLE
cannot run the test data after installing

### ISSUE THREAD

**Issue by ttriche** [chfi/waragraph#17]
```
(base) tim@thinkpad-P15:~/waragraph$ ./target/release/waragraph test/data/A-3105.fa.353ea42.34ee7b1.1576367.smooth.fix.gfa test/data/A-3105.layout.tsv 
[2023-05-26T14:15:52Z WARN  wgpu_hal::gles::egl] No config found!
[2023-05-26T14:15:52Z WARN  wgpu_hal::gles::egl] EGL says it can present to the window but not natively
[2023-05-26T14:15:52Z WARN  wgpu_hal::vulkan::instance] Disabling presentation on 'Intel(R) UHD Graphics (CML GT2)' (id 0x56338c6144a0) because of NV Optimus (on Linux)
parsed 6793 edges
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/tim/.cargo/git/checkouts/raving-wgpu-26431015070e8629/7728766/src/lib.rs:87:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Good point, let's get a backtrace. 

```
# ... with RUST_BACKTRACE=1
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/panicking.rs:84:5
   3: raving_wgpu::State::prepare_window
   4: waragraph::app::window::AppWindowState::init
   5: waragraph::app::App::init_viewer_1d
   6: waragraph::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

OK fine let's run the full backtrace out into a file.  Surely the program won't completely skip STDERR and STDOUT!

```
(base) tim@thinkpad-P15:~/waragraph$ RUST_BACKTRACE=full ./target/release/waragraph test/data/A-3105.fa.353ea42.34ee7b1.1576367.smooth.fix.gfa test/data/A-3105.layout.tsv 2>&1 > backtrace_full.txt
[2023-05-26T14:18:50Z WARN  wgpu_hal::gles::egl] No config found!
[2023-05-26T14:18:50Z WARN  wgpu_hal::gles::egl] EGL says it can present to the window but not natively
[2023-05-26T14:18:50Z WARN  wgpu_hal::vulkan::instance] Disabling presentation on 'Intel(R) UHD Graphics (CML GT2)' (id 0x562a08fc01a0) because of NV Optimus (on Linux)
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/tim/.cargo/git/checkouts/raving-wgpu-26431015070e8629/7728766/src/lib.rs:87:30
stack backtrace:
   0:     0x562a06e16a73 - std::backtrace_rs::backtrace::libunwind::trace::he0156af2558114c2
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562a06e16a73 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e2672bcf5105eb5
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562a06e16a73 - std::sys_common::backtrace::_print_fmt::haa919a14d8d859ec
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x562a06e16a73 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf15e8f9e6884dd5f
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x562a06e383fc - core::fmt::write::he42254d9e3c27115
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/fmt/mod.rs:1202:17
   5:     0x562a06dfbfd5 - std::io::Write::write_fmt::hfb37e0ab3a125c66
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/io/mod.rs:1679:15
   6:     0x562a06dff464 - std::sys_common::backtrace::_print::h8078bdb0e2e92b53
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x562a06dff464 - std::sys_common::backtrace::print::h09fd65486fb9c4f7
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x562a06dff464 - std::panicking::default_hook::{{closure}}::hb89b98c578903f40
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:295:22
   9:     0x562a06dff0a4 - std::panicking::default_hook::h27aa44be03b01ac8
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:314:9
  10:     0x562a06dffa43 - std::panicking::rust_panic_with_hook::he7013d2ea706cde0
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:698:17
  11:     0x562a06e17077 - std::panicking::begin_panic_handler::{{closure}}::hd66fe345adc7bed2
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:588:13
  12:     0x562a06e16bb4 - std::sys_common::backtrace::__rust_end_short_backtrace::ha2b47ffe9f27aed9
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x562a06dff732 - rust_begin_unwind
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:584:5
  14:     0x562a065ac513 - core::panicking::panic_fmt::hbfca70bd08ba6212
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/panicking.rs:142:14
  15:     0x562a065ac452 - core::panicking::panic_bounds_check::had42be473306b825
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/panicking.rs:84:5
  16:     0x562a06857830 - raving_wgpu::State::prepare_window::h8a616cb55d8d7b82
  17:     0x562a066d605d - waragraph::app::window::AppWindowState::init::h47ec9aaafdae7c31
  18:     0x562a0666c02c - waragraph::app::App::init_viewer_1d::h5323681411d8e33e
  19:     0x562a065d7eec - waragraph::main::h8cc159b85ba8d039
  20:     0x562a065d27e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1200e36f5bd50f92
  21:     0x562a065e4159 - std::rt::lang_start::{{closure}}::hb709b23e8c87ff76
  22:     0x562a06dfb408 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h62af992155415807
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/core/src/ops/function.rs:283:13
  23:     0x562a06dfb408 - std::panicking::try::do_call::hcfafbbba7d4f6a6c
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:492:40
  24:     0x562a06dfb408 - std::panicking::try::h7ee1bfcad42abe9b
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:456:19
  25:     0x562a06dfb408 - std::panic::catch_unwind::h009aa132eb8dd7d2
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panic.rs:137:14
  26:     0x562a06dfb408 - std::rt::lang_start_internal::{{closure}}::h93ae259af980c7d0
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/rt.rs:148:48
  27:     0x562a06dfb408 - std::panicking::try::do_call::ha0627c997265a210
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:492:40
  28:     0x562a06dfb408 - std::panicking::try::h64a0afc1377cc785
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panicking.rs:456:19
  29:     0x562a06dfb408 - std::panic::catch_unwind::h1c61ea510b397b89
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/panic.rs:137:14
  30:     0x562a06dfb408 - std::rt::lang_start_internal::ha75927e1903320fe
                               at /build/rustc-Oic09u/rustc-1.65.0+dfsg0ubuntu1/library/std/src/rt.rs:148:20
  31:     0x562a065d8288 - main
  32:     0x7f062f629d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  33:     0x7f062f629e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  34:     0x562a065ac6f5 - _start
  35:                0x0 - <unknown>
```

Just kidding, it absolutely does skip STDERR and STDOUT :man_facepalming: . 

[backtrace_full.txt](https://github.com/chfi/waragraph/files/11576126/backtrace_full.txt)

**Comment by chfi** [comment]
Looks like it's trying and failing to use the Nvidia GPU instead of the integrated Intel chip. Dual GPU setups are always weird, but I just updated the `dev` branch to support the environment variables listed here: https://crates.io/crates/wgpu

On the latest `dev`, try setting `WGPU_ADAPTER_NAME` to `Intel(R) UHD Graphics (CML GT2)` so that the Intel adapter is preferred.
If it still doesn't work, see if you can get the examples in the `wgpu` repo to work: https://github.com/gfx-rs/wgpu/wiki/Running-the-examples
