### ISSUE TITLE
Issues loading in BED or GFF

### ISSUE THREAD

**Issue by brettChapman** [chfi/waragraph#26]
Hi

I'm currently trying to load in a BED or GFF file when loading in the GFA. No gene coordinates are overlayed.

I've tried with a BED file and GFF:

GFF:
```
Morex_v3_chr6H	pgsb	gene	516806175	516807130	.	+	.	ID=HORVU.MOREX.r3.6HG0617490;Name=HORVU.MOREX.r3.6HG0617490;confidence=high;biotype=protein_coding
Morex_v3_chr6H	pgsb	mRNA	516806175	516807130	.	+	.	ID=HORVU.MOREX.r3.6HG0617490.1;Parent=HORVU.MOREX.r3.6HG0617490;confidence=high;biotype=protein_coding;score=***;description=Alpha-amylase;ontology=GO:0003824,GO:0004556,GO:0005509,GO:0005975,GO:0008152,GO:0016787,GO:0016798,GO:0043169,GO:0103025;pfam=PF00128;interpro=IPR006047,IPR017853
Morex_v3_chr6H	pgsb	exon	516806175	516806261	.	+	.	ID=HORVU.MOREX.r3.6HG0617490.1.exon1;Parent=HORVU.MOREX.r3.6HG0617490.1
Morex_v3_chr6H	pgsb	CDS	516806175	516806261	.	+	0	ID=HORVU.MOREX.r3.6HG0617490.1.CDS1;Parent=HORVU.MOREX.r3.6HG0617490.1
Morex_v3_chr6H	pgsb	exon	516806342	516807130	.	+	.	ID=HORVU.MOREX.r3.6HG0617490.1.exon2;Parent=HORVU.MOREX.r3.6HG0617490.1
Morex_v3_chr6H	pgsb	CDS	516806342	516807130	.	+	0	ID=HORVU.MOREX.r3.6HG0617490.1.CDS2;Parent=HORVU.MOREX.r3.6HG0617490.1
Morex_v3_chr6H	pgsb	gene	516809631	516818161	.	+	.	ID=HORVU.MOREX.r3.6HG0617500;Name=HORVU.MOREX.r3.6HG0617500;confidence=high;biotype=protein_coding
Morex_v3_chr6H	pgsb	mRNA	516809631	516818161	.	+	.	ID=HORVU.MOREX.r3.6HG0617500.1;Parent=HORVU.MOREX.r3.6HG0617500;confidence=
```

BED:
```
Morex_v3_chr6H	516475490	516477188	HORVU.MOREX.r3.6HG0617430
Morex_v3_chr6H	516484369	516484851	HORVU.MOREX.r3.6HG0617440
Morex_v3_chr6H	516557345	516558815	HORVU.MOREX.r3.6HG0617450
Morex_v3_chr6H	516560746	516561102	HORVU.MOREX.r3.6HG0617460
Morex_v3_chr6H	516571437	516572907	HORVU.MOREX.r3.6HG0617470
Morex_v3_chr6H	516683252	516684722	HORVU.MOREX.r3.6HG0617480
Morex_v3_chr6H	516806175	516807130	HORVU.MOREX.r3.6HG0617490
Morex_v3_chr6H	516809631	516818161	HORVU.MOREX.r3.6HG0617500
Morex_v3_chr6H	516884746	516886415	HORVU.MOREX.r3.6HG0617510
Morex_v3_chr6H	516889231	516889440	HORVU.MOREX.r3.6HG0617520
Morex_v3_chr6H	525007278	525008959	HORVU.MOREX.r3.6HG0619750
```

I modified the chromosome name to match the path name in the graph, and I'm only including one genome reference in the graph of the 5 genomes.

```
target/release/waragraph barley_pangenome_6H.r516474490-525009959.sorted.gfa barley_pangenome_6H.r516474490-525009959.sorted.final.og.lay.tsv --gff AMY_v2.gff --gff-attr gene
```

and 

```
target/release/waragraph barley_pangenome_6H.r516474490-525009959.sorted.gfa barley_pangenome_6H.r516474490-525009959.sorted.final.og.lay.tsv --bed AMY.bed
```

**Comment by brettChapman** [comment]
Hi @chfi any feedback on this? I tried the web version and had the same issues with including gene labels from a BED file. Thanks

**Comment by chfi** [comment]
In the web version, you need to click on the BED rows in the list you want to toggle annotations on/off for, after you've loaded the BED file. There's also a bug where you have to move the view around a bit (just click & drag the 2D view) before they're actually displayed.
If that still doesn't work, I'd probably have to see the GFA file to be able to debug further.

**Comment by brettChapman** [comment]
Hi @chfi 

I'm having issues with getting the web version to run:

I follow the installation instructions here: https://github.com/chfi/waragraph/tree/web/web

I'm running on a macbook pro M1


```
(base) MUMAC121:web brettchapman$ npx parcel index.html
Server running at http://localhost:1234
🚨 Build failed.

@parcel/transformer-css: Could not resolve module "../lightningcss.darwin-arm64.node" from "/Users/brettchapman/Desktop/waragraph/waragraph/web/node_modules/lightningcss/node/index.js"

  Error: Could not resolve module "../lightningcss.darwin-arm64.node" from "/Users/brettchapman/Desktop/waragraph/waragraph/web/node_modules/lightningcss/node/index.js"
      at NodePackageManager.resolveInternal (/Users/brettchapman/Desktop/waragraph/waragraph/web/node_modules/@parcel/package-manager/lib/index.js:3681:21)
      at NodePackageManager.resolveSync (/Users/brettchapman/Desktop/waragraph/waragraph/web/node_modules/@parcel/package-manager/lib/index.js:3576:29)
      at NodePackageManager.requireSync (/Users/brettchapman/Desktop/waragraph/waragraph/web/node_modules/@parcel/package-manager/lib/index.js:3393:33)
      at m.require (/Users/brettchapman/Desktop/waragraph/waragraph/web/node_modules/@parcel/package-manager/lib/index.js:3418:25)
      at require (node:internal/modules/helpers:119:18)
      at Object.<anonymous> (/Users/brettchapman/Desktop/waragraph/waragraph/web/node_modules/lightningcss/node/index.js:21:22)
      at Module._compile (node:internal/modules/cjs/loader:1233:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
      at Module.load (node:internal/modules/cjs/loader:1091:32)
      at NodePackageManager.load (/Users/brettchapman/Desktop/waragraph/waragraph/web/node_modules/@parcel/package-manager/lib/index.js:3431:15)
```

**Comment by chfi** [comment]
Try `npm i lightningcss` (https://github.com/parcel-bundler/lightningcss/issues/323)

**Comment by brettChapman** [comment]
Hi @chfi Thanks. That worked.

I tried as you suggested with the BED file, but it still doesn't display the gene labels.

I'll attach my zipped up gfa, tsv and bed file here. Thanks.

[example_waragraph.zip](https://github.com/chfi/waragraph/files/14256009/example_waragraph.zip)

**Comment by chfi** [comment]
@brettChapman I pushed a fix to the web branch that should solve it
