### ISSUE TITLE
Cannot open script file 'paths.rhai'

### ISSUE THREAD

**Issue by baozg** [chfi/waragraph#3]
Hi @chfi 

I already installed MoltenVK and successfully installed `waragraph` with `rust` on macOS wiht M1 MacBook.
But after I run the waragraph, it throw a error:
```shell
~/software/waragraph/target/release/waragraph chr1.fasta.gz.0eed25d.c2fac19.5c75112.smooth.final.gfa

[src/graph.rs:247]
[src/graph.rs:253] ix = 0
[src/graph.rs:253] ix = 1
[src/graph.rs:253] ix = 2
[src/graph.rs:253] ix = 3
[src/graph.rs:253] ix = 4
[src/graph.rs:253] ix = 5
[src/graph.rs:253] ix = 6
[src/graph.rs:253] ix = 7
[src/graph.rs:253] ix = 8
[src/graph.rs:253] ix = 9
[src/graph.rs:253] ix = 10
[src/graph.rs:253] ix = 11
[src/graph.rs:253] ix = 12
[src/graph.rs:253] ix = 13
[src/graph.rs:253] ix = 14
[src/graph.rs:253] ix = 15
[src/graph.rs:253] ix = 16
[src/graph.rs:253] ix = 17
[src/graph.rs:253] ix = 18
[src/graph.rs:253] ix = 19
[src/graph.rs:253] ix = 20
[src/graph.rs:253] ix = 21
[src/graph.rs:253] ix = 22
[src/graph.rs:253] ix = 23
[src/graph.rs:253] ix = 24
[src/graph.rs:253] ix = 25
[src/graph.rs:253] ix = 26
[src/graph.rs:253] ix = 27
DEBUG [waragraph] Using default event loop
DEBUG [raving::vk] Created Vulkan entry
DEBUG [raving::vk::init] Creating instance
DEBUG [raving::vk::init] Enumerated required instance extensions
DEBUG [raving::vk::init] getting layer names and pointers
DEBUG [raving::vk::init] Loading instance extension "VK_KHR_surface"
DEBUG [raving::vk::init] Loading instance extension "VK_EXT_metal_surface"
DEBUG [raving::vk::init] Loading instance extension "VK_KHR_get_physical_device_properties2"
DEBUG [raving::vk] Created Vulkan instance
DEBUG [raving::vk] Created window surface
DEBUG [raving::vk::init] Enumerating physical devices
DEBUG [raving::vk::init] Device 0 - "Apple M1 Pro"
INFO [raving::vk::init] Selected physical device: "Apple M1 Pro"
DEBUG [raving::vk::init] Found queue families; graphics: Some(0), present: Some(0), compute: Some(0)
WARN [gpu_allocator::vulkan] There is a memory type that is host visible, but not host coherent. It's time to upgrade our memory allocator to take advantage of this type of memory :)
WARN [gpu_allocator::allocator::free_list_allocator] leak detected: {
    memory type: 0
    memory block: 0
    chunk: {
        chunk_id: 2,
        size: 0x1d4c00,
        offset: 0x0,
        allocation_type: NonLinear,
        name: out,
        backtrace:
    }
}
WARN [gpu_allocator::allocator::free_list_allocator] leak detected: {
    memory type: 1
    memory block: 0
    chunk: {
        chunk_id: 3,
        size: 0xc80000,
        offset: 0x100000,
        allocation_type: Linear,
        name: Path Viewer Slot Cache,
        backtrace:
    }
}
WARN [gpu_allocator::allocator::free_list_allocator] leak detected: {
    memory type: 1
    memory block: 0
    chunk: {
        chunk_id: 2,
        size: 0x100000,
        offset: 0x0,
        allocation_type: Linear,
        name: label-space:viewer-label-space,
        backtrace:
    }
}
Error: Cannot open script file 'paths.rhai': No such file or directory (os error 2)
```

Do you konw how to fix this error?

**Comment by chfi** [comment]
Currently you need to run waragraph from the repo directory, otherwise it can't find the scripts it needs

**Comment by baozg** [comment]
Thanks for promt response. In the repo directory, `waragraph` can run, but it throw another error

```bash
./target/release/waragraph chr1.fasta.gz.0eed25d.c2fac19.5c75112.smooth.final.gfa
[src/graph.rs:247]
[src/graph.rs:253] ix = 0
[src/graph.rs:253] ix = 1
[src/graph.rs:253] ix = 2
[src/graph.rs:253] ix = 3
[src/graph.rs:253] ix = 4
[src/graph.rs:253] ix = 5
[src/graph.rs:253] ix = 6
[src/graph.rs:253] ix = 7
[src/graph.rs:253] ix = 8
[src/graph.rs:253] ix = 9
[src/graph.rs:253] ix = 10
[src/graph.rs:253] ix = 11
[src/graph.rs:253] ix = 12
[src/graph.rs:253] ix = 13
[src/graph.rs:253] ix = 14
[src/graph.rs:253] ix = 15
[src/graph.rs:253] ix = 16
[src/graph.rs:253] ix = 17
[src/graph.rs:253] ix = 18
[src/graph.rs:253] ix = 19
[src/graph.rs:253] ix = 20
[src/graph.rs:253] ix = 21
[src/graph.rs:253] ix = 22
[src/graph.rs:253] ix = 23
[src/graph.rs:253] ix = 24
[src/graph.rs:253] ix = 25
[src/graph.rs:253] ix = 26
[src/graph.rs:253] ix = 27
DEBUG [waragraph] Using default event loop
DEBUG [raving::vk] Created Vulkan entry
DEBUG [raving::vk::init] Creating instance
DEBUG [raving::vk::init] Enumerated required instance extensions
DEBUG [raving::vk::init] getting layer names and pointers
DEBUG [raving::vk::init] Loading instance extension "VK_KHR_surface"
DEBUG [raving::vk::init] Loading instance extension "VK_EXT_metal_surface"
DEBUG [raving::vk::init] Loading instance extension "VK_KHR_get_physical_device_properties2"
DEBUG [raving::vk] Created Vulkan instance
DEBUG [raving::vk] Created window surface
DEBUG [raving::vk::init] Enumerating physical devices
DEBUG [raving::vk::init] Device 0 - "Apple M1 Pro"
INFO [raving::vk::init] Selected physical device: "Apple M1 Pro"
DEBUG [raving::vk::init] Found queue families; graphics: Some(0), present: Some(0), compute: Some(0)
WARN [gpu_allocator::vulkan] There is a memory type that is host visible, but not host coherent. It's time to upgrade our memory allocator to take advantage of this type of memory :)
WARN [waragraph::viewer::app] binding Tab -> Fn("anon$065934b5eb67107c", waragraph::config::ConfigMap, false, 11, 40)
WARN [waragraph::viewer::app] binding F2 -> Fn(anon$772dbcfe1c166171)
WARN [waragraph::viewer::app] binding F1 -> Fn(anon$8413fa9473208af8)
WARN [raving::script::console::frame] bg_color - #{"b": 0.95, "g": 0.95, "r": 0.95}
WARN [raving::script::console::frame] cfg - waragraph::config::ConfigMap
WARN [raving::script::console::frame] font_desc_set - raving::script::console::frame::Resolvable<raving::vk::resource::index::DescSetIx>
WARN [raving::script::console::frame] font_image - raving::script::console::frame::Resolvable<raving::vk::resource::index::ImageIx>
WARN [raving::script::console::frame] font_image_view - raving::script::console::frame::Resolvable<raving::vk::resource::index::ImageViewIx>
WARN [raving::script::console::frame] img_pipeline - raving::script::console::frame::Resolvable<raving::vk::resource::index::PipelineIx>
WARN [raving::script::console::frame] img_shader - raving::script::console::frame::Resolvable<raving::vk::resource::index::ShaderIx>
WARN [raving::script::console::frame] label_color - #{"b": 0.0, "g": 0.0, "r": 0.0}
WARN [raving::script::console::frame] norm_sampler - raving::script::console::frame::Resolvable<raving::vk::resource::index::SamplerIx>
WARN [raving::script::console::frame] out_desc_set - raving::script::console::frame::BindableVar
WARN [raving::script::console::frame] out_image - raving::script::console::frame::BindableVar
WARN [raving::script::console::frame] out_image_view - raving::script::console::frame::BindableVar
WARN [raving::script::console::frame] path_pipeline - raving::script::console::frame::Resolvable<raving::vk::resource::index::PipelineIx>
WARN [raving::script::console::frame] path_shader - raving::script::console::frame::Resolvable<raving::vk::resource::index::ShaderIx>
WARN [raving::script::console::frame] props - waragraph::config::ConfigMap
WARN [raving::script::console::frame] text_pipeline - raving::script::console::frame::Resolvable<raving::vk::resource::index::PipelineIx>
WARN [raving::script::console::frame] text_shader - raving::script::console::frame::Resolvable<raving::vk::resource::index::ShaderIx>
WARN [raving::script::console::frame] unnorm_sampler - raving::script::console::frame::Resolvable<raving::vk::resource::index::SamplerIx>
DEBUG [waragraph::viewer::app] Config: ConfigMap { map: RwLock { data: {"layout.label": #{"x": 14, "y": 2}, "layout.list_bottom_pad": 100, "layout.max_path_name_len": 14, "layout.padding": 2, "layout.slot": #{"h": 18, "w": -10, "x": 0, "y": 36}, "viz.slot_function": "depth_mean"} }, schema: None }
WARN [raving::script::console::frame] Priority { order: Shader, secondary: false } - 3 resolvers
WARN [raving::script::console::frame] Priority { order: Pipeline, secondary: false } - 3 resolvers
WARN [raving::script::console::frame] Priority { order: Image, secondary: false } - 1 resolvers
WARN [raving::script::console::frame] Priority { order: ImageView, secondary: false } - 1 resolvers
WARN [raving::script::console::frame] Priority { order: Sampler, secondary: false } - 2 resolvers
WARN [raving::script::console::frame] Priority { order: DescriptorSet, secondary: false } - 1 resolvers
WARN [raving::script::console::frame] adding sampler
WARN [waragraph::viewer::app] submitting init batches
ERROR [waragraph::gui::layer::image] allocating `image` sublayer def desc set
ERROR [waragraph::gui::layer::image] desc set allocated
thread 'main' panicked at 'cast_slice>TargetAlignmentGreaterAndInputNotAligned', /Users/zbao/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.12.1/src/internal.rs:30:3
stack backtrace:
   0:        0x100e96650 - std::backtrace_rs::backtrace::libunwind::trace::h67adef0ee52f18a6
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x100e96650 - std::backtrace_rs::backtrace::trace_unsynchronized::hfd058563be5f0141
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100e96650 - std::sys_common::backtrace::_print_fmt::h6e3037edf9476a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x100e96650 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1543c132bc4e188c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x100eb3160 - core::fmt::write::hda8e8eb84b49cbfc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:        0x100e93244 - std::io::Write::write_fmt::hb84c8996aec7120c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:        0x100e97e5c - std::sys_common::backtrace::_print::hf5f28b96760f1aab
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x100e97e5c - std::sys_common::backtrace::print::h327d20a60b6bc910
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x100e97e5c - std::panicking::default_hook::{{closure}}::hdf06011cb093de6a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:        0x100e97bc0 - std::panicking::default_hook::hd7ceb942fff7b170
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:        0x100e982f4 - std::panicking::rust_panic_with_hook::h053d4067a63a6fcb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:        0x100e98228 - std::panicking::begin_panic_handler::{{closure}}::hea9e6c546a23e8ff
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  12:        0x100e96b2c - std::sys_common::backtrace::__rust_end_short_backtrace::hd64e012cf32134c6
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x100e97f80 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  14:        0x100ee822c - core::panicking::panic_fmt::hbfde5533e1c0592e
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  15:        0x100ec1314 - bytemuck::internal::something_went_wrong::hd9e2b3c7d6fff18d
  16:        0x100a156e0 - waragraph::postprocessing::EffectDef::new::h44058b78a4d7c358
  17:        0x100961a88 - raving::vk::VkEngine::with_allocators::h8d9403cfcb488fdd
  18:        0x100a15984 - waragraph::postprocessing::test_effect_instance::h9a81aefb0e1176e3
  19:        0x1008ab1d4 - waragraph::main::h4f6c31e8bf647df9
  20:        0x10089b664 - std::sys_common::backtrace::__rust_begin_short_backtrace::h90a9e0206ca9317b
  21:        0x1008ace30 - std::rt::lang_start::{{closure}}::h6a62338e2fb35caa
  22:        0x100e8c2a8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7cd8ae72620b0d1f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  23:        0x100e8c2a8 - std::panicking::try::do_call::h0bbb0f423dd9d86c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  24:        0x100e8c2a8 - std::panicking::try::hdaabe7e5908702af
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  25:        0x100e8c2a8 - std::panic::catch_unwind::h7ee653eae81d0a43
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  26:        0x100e8c2a8 - std::rt::lang_start_internal::{{closure}}::he727754da11a45c1
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  27:        0x100e8c2a8 - std::panicking::try::do_call::h0171064c04d908b7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  28:        0x100e8c2a8 - std::panicking::try::h9c521838fe914345
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  29:        0x100e8c2a8 - std::panic::catch_unwind::hac847f960377a9be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  30:        0x100e8c2a8 - std::rt::lang_start_internal::hef2161f9571a51d7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  31:        0x1008acae8 - _main
WARN [gpu_allocator::allocator::free_list_allocator] leak detected: {
    memory type: 0
    memory block: 0
    chunk: {
        chunk_id: 2,
        size: 0x1d4c00,
        offset: 0x0,
        allocation_type: NonLinear,
        name: out,
        backtrace:
    }
}
WARN [gpu_allocator::allocator::free_list_allocator] leak detected: {
    memory type: 0
    memory block: 0
    chunk: {
        chunk_id: 3,
        size: 0x8000,
        offset: 0x1d4c00,
        allocation_type: NonLinear,
        name: font_image,
        backtrace:
    }
}
WARN [gpu_allocator::allocator::free_list_allocator] leak detected: {
    memory type: 1
    memory block: 0
    chunk: {
        chunk_id: 14,
        size: 0x1000,
        offset: 0xe870b0,
        allocation_type: Linear,
        name: gradient-grayscale,
        backtrace:
    }

```
